name: Microservices Trigger CI

on:
  push:
    branches: [main]
    paths:
      - "src/**"

  # Allows manually building every service
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  detect-changes:
    runs-on: ubuntu-latest

    outputs:
      services: ${{ steps.changed.outputs.services }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect services
        id: changed
        shell: bash
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "Manual run: detecting all services with Dockerfiles"

            SERVICES=$(
              find src \
                -mindepth 2 \
                -maxdepth 2 \
                -type f \
                -name Dockerfile \
                -printf '%h\n' |
              sed 's#^src/##' |
              sort -u |
              jq -R -s -c 'split("\n")[:-1]'
            )
          else
            echo "Push run: detecting changed services"

            SERVICES=$(
              git diff --name-only \
                "${{ github.event.before }}" \
                "${{ github.sha }}" |
              grep '^src/' |
              cut -d'/' -f2 |
              sort -u |
              jq -R -s -c 'split("\n")[:-1]'
            )
          fi

          echo "Detected services: $SERVICES"
          echo "services=$SERVICES" >> "$GITHUB_OUTPUT"

  build-and-push:
    needs: detect-changes

    if: needs.detect-changes.outputs.services != '[]'

    strategy:
      fail-fast: false
      matrix:
        service: ${{ fromJson(needs.detect-changes.outputs.services) }}

    uses: ./.github/workflows/microservice-ci.yaml

    with:
      service: ${{ matrix.service }}
